=== KajalChellappan/Accomodation-APP/Java_Backend/production/thd-accomodation-app/schema-Appdb-users-standardJSON.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "required": [
    "_id",
    "__v",
    "email",
    "password",
    "username"
  ],
  "properties": {
    "_id": {
      "$ref": "#/$defs/ObjectId"
    },
    "__v": {
      "type": "integer"
    },
    "email": {
      "type": "string"
    },
    "password": {
      "type": "string"
    },
    "unique_id": {
      "type": "integer"
    },
    "username": {
      "type": "string"
    }
  },
  "$defs": {
    "ObjectId": {
      "type": "object",
      "properties": {
        "$oid": {
          "type": "string",
          "pattern": "^[0-9a-fA-F]{24}$"
        }
      },
      "required": [
        "$oid"
      ],
      "additionalProperties": false
    }
  }
}

=== KajalChellappan/Accomodation-APP/Java_Backend/production/thd-accomodation-app/Appdb.users.json
[{
  "_id": {
    "$oid": "63b1f88e7753c5b025ebb3de"
  },
  "username": "kc03385",
  "email": "123@gmail.com",
  "password": "5345346346",
  "__v": 0
},
{
  "_id": {
    "$oid": "63b38d2cfccf0e66a94eb9fa"
  },
  "username": "1231211",
  "email": "dfssfd@gmail.com",
  "password": "werwetwet",
  "__v": 0
},
{
  "_id": {
    "$oid": "63b38fdcfccf0e66a94eb9ff"
  },
  "username": "45646",
  "email": "325@gmail.com",
  "password": "fsdfsdf",
  "__v": 0
},
{
  "_id": {
    "$oid": "63c302b8f1d7cc9459883257"
  },
  "username": "khari",
  "email": "kh@gmail.com",
  "password": "$2a$10$AkTtzUfpScCcrs0ssE78dOddsoSts6A.iLrfHfnVmWQFTUr.xcUDq",
  "unique_id": 1,
  "__v": 0
},
{
  "_id": {
    "$oid": "63c327dbb0965c9a3b6d2805"
  },
  "username": "kc03385",
  "email": "k@gmail.com",
  "password": "$2a$10$h/3KZSNYzgM2yqmUZrrrh.6fMhkq/9PLHn3mE/ZuqItPQ0JI1HgQS",
  "unique_id": 2,
  "__v": 0
},
{
  "_id": {
    "$oid": "63c49bff9a5be3f4aad88b4c"
  },
  "username": "kajalhari",
  "email": "kajalhari@gmail.com",
  "password": "$2a$10$u6GDkm9CWqzUq8xFW4ZSW./d82Ts8Z3t6q7L94zlX7WTAOvanQdES",
  "unique_id": 3,
  "__v": 0
},
{
  "_id": {
    "$oid": "63cc626b324188cdd1f21160"
  },
  "username": "admin",
  "email": "admin@gmail.com",
  "password": "$2a$10$exClihjgK/GjHPnccTOZiu8f1yZUJeW6Wzp1bJskxDpHd4FkalIFe",
  "unique_id": 4,
  "__v": 0
},
{
  "_id": {
    "$oid": "63d3d04d7b085406847acffb"
  },
  "username": "sonya",
  "email": "sonya@gmail.com",
  "password": "123456",
  "unique_id": 5,
  "__v": 0
},
{
  "_id": {
    "$oid": "63d40bf35f3b691357eae8a5"
  },
  "username": "hari",
  "email": "hari@gmail.com",
  "password": "$2a$10$hOA9v8K0pLHEO4Jle1Kts.3JV3PQbtrwF/IQ.Em1lhiQZxu56esmW",
  "unique_id": 6,
  "__v": 0
},
{
  "_id": {
    "$oid": "63d582e63d4aa099ffceeeb9"
  },
  "username": "kc03385",
  "email": "kh@gmail.com",
  "password": "$2a$10$G3Ys1qTxukqyEbi4aVmNAuPS2.tyCxvwTlOI/IlBiThxqF2MuxDUK",
  "unique_id": 7,
  "__v": 0
},
{
  "_id": {
    "$oid": "63d591773d4aa099ffceeebd"
  },
  "username": "gg",
  "email": "gg",
  "password": "$2a$10$ZxsY0UG0R2hbWLGhRDfP/.6wNjWNCisljj99R93PRxcHl8pS73Kf.",
  "unique_id": 8,
  "__v": 0
},
{
  "_id": {
    "$oid": "63d591da3d4aa099ffceeec1"
  },
  "username": "gg",
  "email": "kh@gmail.com",
  "password": "$2a$10$TkWqfqohTRkk9wvtHVZCT.2ELEoTnSkCk6mkZB30VmWA.bBe/Nuuu",
  "unique_id": 9,
  "__v": 0
},
{
  "_id": {
    "$oid": "63d591fe3d4aa099ffceeec5"
  },
  "username": "ff",
  "email": "ff",
  "password": "$2a$10$LnSRGKBQ2whWq7p4aww1w.uzwNbsn5Q3OPIvaerYF6DmSZyCV0blS",
  "unique_id": 10,
  "__v": 0
},
{
  "_id": {
    "$oid": "63d592913d4aa099ffceeed3"
  },
  "username": "gg",
  "email": "hh",
  "password": "$2a$10$/PdyK/1h4XmuQrsT9.9T3e6pp9.IGxlT8LXY23Wv7bCPi8phaseOi",
  "unique_id": 11,
  "__v": 0
},
{
  "_id": {
    "$oid": "63d592d93d4aa099ffceeed7"
  },
  "username": "ds",
  "email": "dsd",
  "password": "$2a$10$4ukrJN1g4vQOGanPhTslpepWXEy777N.uBwQ1FetQAh033HuLfoWS",
  "unique_id": 12,
  "__v": 0
},
{
  "_id": {
    "$oid": "63d593a23d4aa099ffceeee1"
  },
  "username": "fff",
  "email": "ff",
  "password": "$2a$10$ODOnn9xsMoRo/v06GIgo8.FdazWiTV0weOBtF71VRkXYk8sP5KGV6",
  "unique_id": 13,
  "__v": 0
},
{
  "_id": {
    "$oid": "63d595163d4aa099ffceeee5"
  },
  "username": "hh",
  "email": "hh",
  "password": "$2a$10$z3DZg8Nyg1Rp.JFX1gb7/uzyUyXGsnM3e.szkh5xgmDNC8u3oZ7ui",
  "unique_id": 14,
  "__v": 0
},
{
  "_id": {
    "$oid": "68362eabb1bdb9a0946403e7"
  },
  "username": "kcmain",
  "email": "kajal@gmail.com",
  "password": "$2a$10$x5GZaRNoZ0SWEfLmC9QjYeSZrYSLn596E5OoXr8rZYSBd4x/TVSzi",
  "unique_id": 15,
  "__v": 0
}]
